{
 "title": "EcoFlow Status",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Battery Level",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  BATTERY_LEVEL\nFROM stats\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Remaining Power in Hours",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A / 60", "type": "math" }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  BATTERY_TEMP\nFROM stats\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  BATTERY_LEVEL\nFROM stats\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Remaining Power in Hours",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Hours" }
   ],
   "targets": [
    { "expression": "$A / 60", "type": "math" }
   ]
  },
  {
   "title": "Battery Temperature",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  BATTERY_TEMP\nFROM stats\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Watts In & Out",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  AC_IN_WATTS\nFROM stats\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  SOLAR_IN_WATTS\nFROM stats\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    },
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  AC_OUT_WATTS\nFROM stats\nWHERE\n  $__unixEpochFilter(timestamp)\nORDER BY timestamp"
    }
   ]
  }
 ]
}